using System.Text;
using AgentSeat.Core.Models;

namespace AgentSeat.Core.Services;

public sealed record SunshineInstancePaths(
    string AppsFile,
    string StateFile,
    string LogFile,
    string PrivateKeyFile,
    string CertificateFile);

public static class SunshineConfigurationBuilder
{
    public static string Build(SeatDefinition seat, SunshineInstancePaths paths)
    {
        ArgumentNullException.ThrowIfNull(seat);
        ArgumentNullException.ThrowIfNull(paths);
        _ = SunshinePorts.FromBasePort(seat.SunshineBasePort);

        var values = new (string Name, string Value)[]
        {
            ("port", seat.SunshineBasePort.ToString(System.Globalization.CultureInfo.InvariantCulture)),
            ("sunshine_name", $"AgentSeat - {seat.DisplayName}"),
            ("locale", "ko"),
            ("system_tray", "disabled"),
            ("notify_pre_releases", "disabled"),
            ("upnp", "disabled"),
            ("address_family", "ipv4"),
            ("origin_web_ui_allowed", "pc"),
            ("lan_encryption_mode", "1"),
            ("wan_encryption_mode", "2"),
            ("keyboard", "enabled"),
            ("mouse", "enabled"),
            ("controller", "enabled"),
            ("install_steam_audio_drivers", "disabled"),
            ("dd_configuration_option", "disabled"),
            ("file_apps", NormalizePath(paths.AppsFile)),
            ("file_state", NormalizePath(paths.StateFile)),
            ("credentials_file", NormalizePath(paths.StateFile)),
            ("log_path", NormalizePath(paths.LogFile)),
            ("pkey", NormalizePath(paths.PrivateKeyFile)),
            ("cert", NormalizePath(paths.CertificateFile))
        };

        var output = new StringBuilder();
        output.AppendLine("# Generated by AgentSeat. Per-seat applications and pairing state are stored separately.");
        foreach (var (name, value) in values)
        {
            ValidateValue(name, value);
            output.Append(name).Append(" = ").AppendLine(value);
        }

        return output.ToString();
    }

    private static string NormalizePath(string path) => Path.GetFullPath(path).Replace('\\', '/');

    private static void ValidateValue(string name, string value)
    {
        if (string.IsNullOrWhiteSpace(value) || value.Contains('\r') || value.Contains('\n'))
        {
            throw new ArgumentException($"Sunshine configuration value '{name}' is invalid.", nameof(value));
        }
    }
}
